title: People-centric Evolutionary System (PES)
description: a new machine learning system that combines the flexibility of genetic-based machine learning algorithms, dimensionality reduction, data visualisation, and human insights to learn competitive and interpretable predictive models and business rules.
